FORMAT: 1A
HOST: https://punny-names.herokuapp.com

# punny-names

Punny names is a API allowing generation of punny names.

# Group names

## Names Collection [/api/names{?limit,offset,seed}]

+ Parameters
    + limit (number, optional) - the number of names generated
        + Default: `10`
    + offset (number, optional) - the pagination offset
        + Default: `0`
    + seed (number, optional) - the generator seed
        + Default: `1234`

### List names [GET]

Generate a list of names.

+ Response 200 (application/json)

        {
          "links": {
            "self": "{HOST}/api/names?limit=10&offset=0&seed=1234",
            "next": "{HOST}/api/names?limit=10&offset=1&seed=1234"
          },
          "meta": {
            "limit": 10,
            "offset": 0,
            "seed": 1234
          },
          "data": [
            {
              "type": "names",
              "id": "1",
              "attributes": {
                "first": "alain",
                "last": "mergions"
              }
            },
            {
              "type": "names",
              "id": "2",
              "attributes": {
                "first": "dimitri",
                "last": "nassimilable"
              }
            },
            {
              "type": "names",
              "id": "3",
              "attributes": {
                "first": "alain",
                "last": "diens"
              }
            },
            {
              "type": "names",
              "id": "4",
              "attributes": {
                "first": "alain",
                "last": "formassions"
              }
            },
            {
              "type": "names",
              "id": "5",
              "attributes": {
                "first": "alain",
                "last": "sère"
              }
            },
            {
              "type": "names",
              "id": "6",
              "attributes": {
                "first": "alain",
                "last": "terjetait"
              }
            },
            {
              "type": "names",
              "id": "7",
              "attributes": {
                "first": "alain",
                "last": "tubâmes"
              }
            },
            {
              "type": "names",
              "id": "8",
              "attributes": {
                "first": "fabiola",
                "last": "çassiez"
              }
            },
            {
              "type": "names",
              "id": "9",
              "attributes": {
                "first": "absolon",
                "last": "gue-vue"
              }
            },
            {
              "type": "names",
              "id": "10",
              "attributes": {
                "first": "emma",
                "last": "noquerais"
              }
            }
          ]
        }

## Name [/api/names/{id}{?seed}]

+ Parameters
    + id (number) - the name identifier
    + seed (number, optional) - the generator seed
        + Default: `1234`

### Retrieve name [GET]

Get a name by id.

+ Response 200 (application/json)

        {
          "links": {
            "self": "{HOST}/api/names/1?seed=1234"
          },
          "meta": {
            "seed": 1234
          },
          "data": {
            "type": "names",
            "id": "1",
            "attributes": {
              "first": "alain",
              "last": "mergions"
            }
          }
        }