FORMAT: 1A
HOST: https://punny-names.herokuapp.com

# punny-names

Punny names is a API allowing generation of punny names.

# Group names

## Names Collection [/api/names{?limit,skip,seed}]

+ Parameters
    + limit (number, optional) - the number of names generated
        + Default: `10`
    + skip (number, optional) - the pagination offset
        + Default: `0`
    + seed (number, optional) - the generator seed
        + Default: `1234`

### List names [GET]

Generate a list of names.

+ Response 200 (application/json)

        [
          {
            "id": 1,
            "first": "alain",
            "last": "mergions"
          },
          {
            "id": 2,
            "first": "dimitri",
            "last": "nassimilable"
          },
          {
            "id": 3,
            "first": "alain",
            "last": "diens"
          },
          {
            "id": 4,
            "first": "alain",
            "last": "formassions"
          },
          {
            "id": 5,
            "first": "alain",
            "last": "sère"
          },
          {
            "id": 6,
            "first": "alain",
            "last": "terjetait"
          },
          {
            "id": 7,
            "first": "alain",
            "last": "tubâmes"
          },
          {
            "id": 8,
            "first": "fabiola",
            "last": "çassiez"
          },
          {
            "id": 9,
            "first": "absolon",
            "last": "gue-vue"
          },
          {
            "id": 10,
            "first": "emma",
            "last": "noquerais"
          }
        ]

## Name [/api/names/{id}{?seed}]

+ Parameters
    + id (number) - the name identifier
    + seed (number, optional) - the generator seed
        + Default: `1234`

### Retrieve name [GET]

Get a name by id.

+ Response 200 (application/json)

        {
          "id": 1,
          "first": "alain",
          "last": "mergions"
        }